### ISSUE TITLE
Nextjs SSR prints warning on useLayoutEffect

### ISSUE THREAD

**Issue by ichn-hu** [Cusdis/sdk#4]
If we use the react component in SSR, the following warning will be generated

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at ReactCusdis (/home/ichn/Documents/notion-blog-v2/node_modules/react-cusdis/dist/ReactCusdis.js:7:26)
    at div
    at RenderPost (/home/ichn/Documents/notion-blog-v2/.next/server/pages/blog/[slug].js:2970:3)
    at MyApp (/home/ichn/Documents/notion-blog-v2/.next/server/pages/_app.js:37:3)
    at AppContainer (/home/ichn/Documents/notion-blog-v2/node_modules/next/dist/server/render.js:293:29)
```

**Comment by lord5et** [comment]
Same here
```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at ReactCusdis (E:\nextjs-blog\node_modules\react-cusdis\dist\ReactCusdis.js:7:26)
    at footer
    at main
    at div
    at Layout (webpack-internal:///./components/layout.tsx:26:19)
    at Post (webpack-internal:///./pages/posts/[id].tsx:25:17)
    at App (webpack-internal:///./pages/_app.tsx:11:16)
    at InnerApp
    at StyleRegistry (E:\nextjs-blog\node_modules\styled-jsx\dist\stylesheet-registry.js:231:34)
    at AppContainer (E:\nextjs-blog\node_modules\next\dist\server\render.js:340:29)
    at AppContainerWithIsomorphicFiberStructure (E:\nextjs-blog\node_modules\next\dist\server\render.js:370:57)
    at div
    at Body (E:\nextjs-blog\node_modules\next\dist\server\render.js:638:21)
```
